"""Initial tables

Revision ID: e5dc2ec5aac7
Revises: 
Create Date: 2026-05-27 23:44:54.164116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5dc2ec5aac7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('technical_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_sent', sa.String(), nullable=False),
    sa.Column('gemini_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data_ohlcv',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('time', 'symbol', 'timeframe')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('encrypted_api_key', sa.String(), nullable=False),
    sa.Column('encrypted_secret', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('stop_loss', sa.Numeric(), nullable=False),
    sa.Column('take_profit', sa.Numeric(), nullable=True),
    sa.Column('volume_percentage', sa.Numeric(), nullable=False),
    sa.Column('is_recovery', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("SELECT create_hypertable('market_data_ohlcv', 'time');")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('market_data_ohlcv')
    op.drop_table('ai_analysis_logs')
    # ### end Alembic commands ###
